
table_columns_visible:
    Qualimap:
        avg_gc: True
        median_insert_size: True
        10_x_pc: True
        median_coverage: True
        mean_coverage: True
        percent_aligned: True
        mapped_reads: True
        total_reads: True
        general_error_rate: False
    FastQC:
        percent_duplicates: False
        percent_gc: False
        avg_sequence_length: False
        percent_fails: False
        total_sequences: False
    iVar:
        reads_too_short_after_trimming: False
        reads_outside_primer_region: False
        trimmed_reads: False
        mapped_reads: False

table_columns_placement:
    QualiMap:
        total_reads: 800
        mapped_reads: 860
        percentage_aligned: 900
        10_x_pc: 950
        median_coverage: 960
        mean_coverage: 965
        median_insert_size: 970
        avg_gc: 990
    my_genstats:
        P25 Ins. size: 980
        Pct >=Q30: 1800

qualimap_config:
  general_stats_coverage:
    - 10
  general_stats_coverage_hidden:
    - 1
    - 5
    - 30
    - 50

plots_force_interactive: True

max_table_rows: 10000

remove_sections:
    - qualimap-coverage-histogram
    - qualimap-cumulative-genome-fraction-coverage
    - qualimap-insert-size-histogram
    - qualimap-gc-distribution
    
# custom_plot_config:
#     qualimap_coverage_histogram:
#         logswitch: True
#         logswitch_active: True
#         logswitch_label: 'Log10'
#     qualimap_genome_fraction:
#         logswitch: True
#         logswitch_active: True
#         logswitch_label: 'Log10'
