name: Continuous integration unit testing and lint

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: defaults
    - name: Install dependencies
      run: |
        conda create --yes -n env_name python=${{ matrix.python-version }}
        conda activate env_name
        conda install numpy=1.21.2 
        conda install boto3
        conda install -c bioconda qualimap
        conda install -c bioconda minimap2
        conda install -c bioconda samtools
        pip install multiqc
        pip install nwalign3
        pip install pandas==1.4.1
        pip install fastaparser        
        
    - name: Lint with flake8
      run: |
        conda activate env_name
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda activate env_name
        conda install pytest
        which python
        pip install -e . --no-deps
        pytest
